services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:80"
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: passwort
#      MYSQL_DATABASE: symfony
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: symfony
#    ports:
#      - "3306:3306"
